[package]
name = "easy-configuration-format"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Simple and intuitive file format for settings / configurations"
repository = "https://github.com/What42Pizza/rust-easy-configuration-format"
readme = "readme.md"
keywords = []
categories = []
